### ISSUE TITLE
[Bug] Pop-up flickering

### ISSUE THREAD

**Issue by BaccanoMob** [Suwayomi/Tachidesk-JUI#10]
## Steps to reproduce
1. Go to Reader settings (or any other setting with pop-up windows).
2. Click two or more setting with pop-ups without closing the opened pop-up.

### Expected behavior
Prevent the app from opening an new pop-up.

### Actual behavior
Allows a new pop-ups to open and pop-up windows start flickering.

### Additional info
This is not an issue with the reader (could open multiple chapters) but only in the setting.

**Comment by Syer10** [comment]
Not a issue with the latest updates, forced open popups are not enabled
