### ISSUE TITLE
[App Icon in windows 10] 

### ISSUE THREAD

**Issue by objestik** [Suwayomi/Tachidesk-JUI#22]
on Windows the app icon when installing is just the Kotlin icon. why not make change the icon to make the one's you're using on linux? 
![app icon](https://user-images.githubusercontent.com/28157614/132264016-a8e1a119-e52e-472c-b17f-e7052eddd589.PNG)

I think it'd look better this way and to easily distinguish it from other programs.

**Comment by objestik** [comment]
use this one instead. 
![icon](https://user-images.githubusercontent.com/28157614/132264084-391c419b-0570-4b41-b255-4356aca39488.png)

**Comment by Syer10** [comment]
The icon is already set for next release 👍

**Comment by objestik** [comment]
glad to hear it :)
