### ISSUE TITLE
[Feature Request] Replacing the included tachidesk with the more updated version.

### ISSUE THREAD

**Issue by MagicalDrizzle** [Suwayomi/Tachidesk-JUI#24]
Is it possible to replace the included tachidesk jar with the more updated version in the main repo?
I tried to just edit it with 7zip but it fails with 'not a valid jar' as expected.

**Comment by Syer10** [comment]
There is a few things you have to do to update Tachidesk.jar
1. Chance the referenced Tachidesk-Server commit located [here](https://github.com/Suwayomi/Tachidesk-JUI/blob/master/buildSrc/src/main/kotlin/Config.kt#L8), you do this by clicking on the latest commit in the repo and copying the last part of the url.
2. Change the version that Tachidesk is on [here](https://github.com/Suwayomi/Tachidesk-JUI/blob/master/buildSrc/src/main/kotlin/Config.kt#L4)
3. Get the commit count and replace the value [here](https://github.com/Suwayomi/Tachidesk-JUI/blob/master/buildSrc/src/main/kotlin/Config.kt#L6), you can find it by looking at the github page and there will be a ### Commits section
4. After all that you can run a gradle build and it will update Tachidesk.jar by itself

**Comment by Syer10** [comment]
If you dont want to do it in the code, you can you run the server externally and use the server settings to connect to it instead of having Tachidesk-JUI run the server on its own

**Comment by MagicalDrizzle** [comment]
Right, how may I run it externally?

**Comment by Syer10** [comment]
Same as normal Tachidesk-Server, run one of the launchers 😄

**Comment by MagicalDrizzle** [comment]
yeah I realized it 3 seconds after posting the comment, my apologies
