### ISSUE TITLE
[Bug] Mangadex Blank Settings 

### ISSUE THREAD

**Issue by py7hon** [Suwayomi/Tachidesk-JUI#28]
![1637769263](https://user-images.githubusercontent.com/29944979/143269498-f4efa020-a3fc-4818-aa0b-c8acc29ba0ec.png)

## Device information
- Tachidesk-JUI version: Tachidesk-JUI v1.1.2
- Operating System: ArchLinux
- Desktop Environment: OpenBox
- Server Type: Internal
- Client JVM version: 17.0.1.u12-1
- Server JVM version: Same as Client

## Steps to reproduce
1. Fresh Install Extension Mangadex
2. Open Sources and Settings

[logs.txt](https://github.com/Suwayomi/Tachidesk-JUI/files/7596994/logs.txt)

**Comment by Syer10** [comment]
They switched to a new type of preference dialog. Support is on the to-do list for Tachidesk-Server

**Comment by Syer10** [comment]
Its fixed in the preview

**Comment by AriaMoradi** [comment]
Fixed in v1.2.0
