### ISSUE TITLE
[Feature Request] Add Dutch translation

### ISSUE THREAD

**Issue by Reacien** [Suwayomi/Tachidesk-JUI#37]
## What feature should be added to Tachidesk-JUI?
Add a Dutch translation to the Weblate project.

##  Why/Project's Benefit/Existing Problem
My mother tongue is Dutch and I would like to translate and use it in my own language.

**Comment by Syer10** [comment]
Anyone should be able to add their chosen language to the Weblate I believe, others have done that before translating the app to their chosen language. You can also join the [discord](https://discord.gg/wgPyb7hE5d) if you need any help or advice with how to translate the app.
