### ISSUE TITLE
[Bug] After the reader finishes loading the image, the cpu usage is still high

### ISSUE THREAD

**Issue by sixpoints** [Suwayomi/Tachidesk-JUI#50]
## Device information
- Tachidesk-JUI version: v1.3.0
- Operating System: Windows 10 (19044.1706)
- Desktop Environment: N/A
- Server Type: remote server running Tachidesk-Server-v0.6.3-r1100-linux-x64
- Client JVM version: Java 17.0.3
- Server JVM version: Same as Client

## Steps to reproduce
1. Run Tachidesk-JUI.jar
2. Open a comic in the reader

### Expected behavior
After the reader finishes loading,  the cpu usage should be lower.

### Actual behavior
After the reader finishes loading the image and waiting for a few minutes, the cpu usage is still high(about 20%).

## Other details
Also no more log in the rolling.log during high cpu usage after loading.

**Comment by Syer10** [comment]
This should be fixed in the latest preview, let me know if it still happens
