### ISSUE TITLE
[Bug] Update not showing new chapters

### ISSUE THREAD

**Issue by syedaliasad649** [Suwayomi/Tachidesk-JUI#53]
## Device information
- Tachidesk-JUI version: achidesk-jui_1.3.0-1
- Operating System: Ubuntu 20.04
- Desktop Environment: Gnome 3.36.8
- Server Type: Internal
- Client JVM version: openjdk 11.0.15
- Server JVM version: Same as Client 

## Steps to reproduce
1. Open JUI
2. Refresh in a manga in library to find that your page says 'No chapter found', refresh again to view the same old.

### Expected behavior
To view new chaps
### Actual behavior
A text appears saying 'No chapters found'

**Comment by syedaliasad649** [comment]
Scratch the latter part, that was just me being dumb.

**Comment by Vikng412** [comment]
How do you refresh the whole library at once?

**Comment by Syer10** [comment]
Should work now
