### ISSUE TITLE
[Feature Request] Update checker

### ISSUE THREAD

**Issue by Syer10** [Suwayomi/Tachidesk-JUI#8]
## What feature should be added to TachideskJUI?
Every certain period of time the app should check for updates

##  Why/Project's Benefit/Existing Problem
Will help users keep updated

**Comment by Vikng412** [comment]
how do you refresh the whole library at once?
Is there a way yet to update only one category like tachiyomi?

**Comment by Robonau** [comment]
this isn't the place to ask questions, try the discord
