### ISSUE TITLE
[Feature Request] Ability to remove DATE from downloaded file name, or force to be full date, like "Feb 24, 2024"

### ISSUE THREAD

**Issue by GenerlAce** [Suwayomi/Tachidesk-JUI#84]
---

## What feature should be added to Tachidesk-JUI?
    Is there an ability to remove the DATE from the downloaded chapter name, or a way to have it always be the actual date vs. "5 hours ago..." or "1 day ago".

##  Why/Project's Benefit/Existing Problem
   For regular downloads, the date is nice, but on regularly updated manga chapters it doesnt show a full date like "Dec 07, 2023", but new chapters (depending on how soon after its released) will download with a name like "Chapter 100_Super Bad Guy 18 hours ago". Is there a setting to force the proper date to always be the name, or an overall ability to remove the date entirely. Thank you.

**Comment by Syer10** [comment]
This is a source issue, we don't add dates to the chapter titles ourself. Open a issue with your source repo.
